"""Type stubs for the kitest extension; keep in sync with src/lib.rs."""

class DcSupply:
    def __init__(self, node: str, volts: float) -> None: ...

class AcSupply:
    def __init__(self, node: str) -> None: ...
    def bias(self, bias: float) -> AcSupply: ...
    def magnitude(self, magnitude: float) -> AcSupply: ...

class Pulse:
    @staticmethod
    def step(low: float, high: float) -> Pulse: ...
    def delay(self, delay: float) -> Pulse: ...
    def rise(self, rise: float) -> Pulse: ...
    def fall(self, fall: float) -> Pulse: ...
    def width(self, width: float) -> Pulse: ...
    def period(self, period: float) -> Pulse: ...

class Sin:
    def __init__(self, offset: float, amplitude: float, freq: float) -> None: ...
    def delay(self, delay: float) -> Sin: ...

class TranSource:
    @staticmethod
    def pulse(node: str, pulse: Pulse) -> TranSource: ...
    @staticmethod
    def sin(node: str, sin: Sin) -> TranSource: ...

class Sweep:
    Dec: Sweep
    Oct: Sweep
    Lin: Sweep

class Ac:
    def __init__(
        self, sweep: Sweep, points: int, fstart: float, fstop: float
    ) -> None: ...

class Tran:
    def __init__(self, step: float, stop: float) -> None: ...

class Tolerance:
    @staticmethod
    def abs(v: float) -> Tolerance: ...
    @staticmethod
    def pct(p: float) -> Tolerance: ...

class Voltage:
    def volts(self) -> float: ...
    def near(self, expected: float, tolerance: Tolerance) -> bool: ...

class Signal:
    def time(self) -> list[float]: ...
    def values(self) -> list[float]: ...
    def settles_to(
        self, target: float, tolerance: Tolerance, window: float
    ) -> bool: ...
    def overshoot(self, target: float) -> float: ...

class Response:
    def frequency(self) -> list[float]: ...
    def values(self) -> list[complex]: ...
    def gain_db_at(self, frequency: float) -> float | None: ...
    def phase_deg_at(self, frequency: float) -> float | None: ...

class OperatingPoint:
    def node(self, node: str) -> Voltage | None: ...

class Waveforms:
    def node(self, node: str) -> Signal | None: ...

class Spectra:
    def node(self, node: str) -> Response | None: ...

class Ngspice:
    def __init__(self) -> None: ...
    def run_op(
        self, netlist: str, supplies: list[DcSupply]
    ) -> OperatingPoint: ...
    def run_ac(
        self, netlist: str, supplies: list[AcSupply], params: Ac
    ) -> Spectra: ...
    def run_tran(
        self, netlist: str, sources: list[TranSource], params: Tran
    ) -> Waveforms: ...

def version() -> str: ...
def export_netlist(sch: str) -> str: ...
