"""Type stubs for the kitest extension; keep in sync with src/lib.rs."""

class DcSupply:
    def __init__(self, node: str, volts: float) -> None: ...

class Tolerance:
    @staticmethod
    def abs(v: float) -> Tolerance: ...
    @staticmethod
    def pct(p: float) -> Tolerance: ...

class Voltage:
    def volts(self) -> float: ...
    def near(self, expected: float, tolerance: Tolerance) -> bool: ...

class OperatingPoint:
    def node(self, node: str) -> Voltage | None: ...

class Ngspice:
    def __init__(self) -> None: ...
    def run_op(
        self, netlist: str, supplies: list[DcSupply]
    ) -> OperatingPoint: ...

def version() -> str: ...
