# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "Ac",
    "AcSupply",
    "Check",
    "CheckError",
    "Config",
    "ConfigError",
    "Corner",
    "DcSupply",
    "Design",
    "Frequency",
    "KicadError",
    "KitestError",
    "ModelError",
    "Netlist",
    "NetlistError",
    "Ngspice",
    "OperatingPoint",
    "Outcome",
    "Power",
    "Probe",
    "ProbeError",
    "Pulse",
    "Rail",
    "Report",
    "Response",
    "Signal",
    "SimulationError",
    "Sin",
    "Spectra",
    "SupplyError",
    "Sweep",
    "Tolerance",
    "Tone",
    "Tran",
    "TranSource",
    "Transient",
    "Voltage",
    "check_project",
    "export_design",
    "version",
]

@typing.final
class Ac:
    def __new__(cls, sweep: Sweep, *, points: builtins.int, fstart: builtins.float, fstop: builtins.float) -> Ac: ...

@typing.final
class AcSupply:
    def __new__(cls, node: builtins.str) -> AcSupply: ...
    def bias(self, bias: builtins.float) -> AcSupply: ...
    def magnitude(self, magnitude: builtins.float) -> AcSupply: ...

@typing.final
class Check:
    r"""
    The outcome of an assertion: truthy when it passed, and printed as what
    was measured against what was expected.
    """
    def __bool__(self) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

class CheckError(KitestError):
    r"""
    A project's probes cannot be checked: a bad Expect field, or a failure reading or simulating the design.
    """
    ...

@typing.final
class Config:
    @staticmethod
    def for_project(directory: builtins.str) -> Config:
        r"""
        Load `kitest.toml` from `directory`, or an empty config if it has none.
        """
    @staticmethod
    def load(path: builtins.str) -> Config:
        r"""
        Load the config file at `path`.
        """
    def supplies(self) -> builtins.dict[builtins.str, builtins.list[builtins.float]]:
        r"""
        Voltages for each rail by full net name.
        """
    def model_libraries(self) -> builtins.list[builtins.str]:
        r"""
        Project model library paths, resolved against the config's directory.
        """

class ConfigError(KitestError):
    r"""
    kitest.toml is invalid.
    """
    ...

@typing.final
class Corner:
    def voltages(self) -> builtins.list[tuple[builtins.str, builtins.float]]:
        r"""
        The SPICE node and voltage of every source kitest adds.
        """
    def dc_supplies(self) -> builtins.list[DcSupply]:
        r"""
        Supplies for `Ngspice.run_op`.
        """
    def tran_sources(self) -> builtins.list[TranSource]:
        r"""
        Constant sources for `Ngspice.run_tran`.
        """
    def ac_supplies(self) -> builtins.list[AcSupply]:
        r"""
        Biased supplies with no AC stimulus, for `Ngspice.run_ac`.
        """

@typing.final
class DcSupply:
    def __new__(cls, node: builtins.str, volts: builtins.float) -> DcSupply: ...

@typing.final
class Design:
    def rails(self) -> builtins.list[builtins.str]:
        r"""
        Net names created by power symbols, sorted.
        """
    def netlist(self, libraries: typing.Sequence[builtins.str] = []) -> Netlist:
        r"""
        The SPICE netlist, binding models from the library files at
        `libraries` first and the bundled library after them.
        """
    def probes(self) -> builtins.list[Probe]:
        r"""
        Every probe in the schematic, in component order.
        """
    def probe(self, name: builtins.str) -> Probe:
        r"""
        The probe named `name`.
        """
    def power(self, supplies: typing.Mapping[builtins.str, typing.Sequence[builtins.float]] = {}) -> Power:
        r"""
        Resolve power rails against voltages declared by full net name, as
        in `kitest.toml`'s `[supplies]`.
        """

@typing.final
class Frequency:
    def hertz(self) -> builtins.float:
        r"""
        The value in hertz.
        """
    def near(self, expected: builtins.float, tolerance: Tolerance) -> Check:
        r"""
        Whether the frequency is within `tolerance` of `expected`.
        """
    def __repr__(self) -> builtins.str: ...

class KicadError(KitestError):
    r"""
    KiCad export failed.
    """
    ...

class KitestError(builtins.Exception):
    r"""
    Base class of every error kitest raises.
    """
    ...

class ModelError(KitestError):
    r"""
    A model library is invalid.
    """
    ...

@typing.final
class Netlist:
    def text(self) -> builtins.str:
        r"""
        The netlist body to pass to `Ngspice`.
        """
    def defaulted(self) -> builtins.list[builtins.str]:
        r"""
        Parts simulated on a default model because no library covers them.
        """

class NetlistError(KitestError):
    r"""
    A design cannot be turned into a netlist.
    """
    ...

@typing.final
class Ngspice:
    def __new__(cls) -> Ngspice: ...
    def run_op(self, netlist: builtins.str, supplies: typing.Sequence[DcSupply]) -> OperatingPoint: ...
    def run_ac(self, netlist: builtins.str, supplies: typing.Sequence[AcSupply], params: Ac) -> Spectra: ...
    def run_tran(self, netlist: builtins.str, sources: typing.Sequence[TranSource], params: Tran) -> Transient: ...

@typing.final
class OperatingPoint:
    def node(self, node: builtins.str) -> Voltage: ...
    def nodes(self) -> builtins.list[builtins.str]: ...

@typing.final
class Outcome:
    r"""
    One probe's result at one corner.
    """
    def probe(self) -> builtins.str:
        r"""
        The probe's name.
        """
    def reference(self) -> builtins.str:
        r"""
        The probe's reference designator.
        """
    def net(self) -> builtins.str:
        r"""
        The net the probe sits on.
        """
    def corner(self) -> builtins.list[tuple[builtins.str, builtins.float]]:
        r"""
        The voltage of each rail kitest sourced, by SPICE node.
        """
    def check(self) -> typing.Optional[Check]:
        r"""
        The check, or `None` for a probe with no `Expect`.
        """
    def __bool__(self) -> builtins.bool:
        r"""
        False only for a check that ran and failed.
        """

@typing.final
class Power:
    def rails(self) -> builtins.list[Rail]:
        r"""
        Every resolved rail, sorted by full net name.
        """
    def corners(self) -> builtins.list[Corner]:
        r"""
        Every combination of sourced rail voltages.
        """

@typing.final
class Probe:
    def name(self) -> builtins.str:
        r"""
        The probe's Value, or its net's name when Value is empty.
        """
    def net(self) -> builtins.str:
        r"""
        The name of the net the probe sits on.
        """
    def expect(self) -> typing.Optional[builtins.str]:
        r"""
        The probe's Expect field, if it has one.
        """
    def reference(self) -> builtins.str:
        r"""
        The probe's reference designator, such as `PRB1`.
        """

class ProbeError(KitestError):
    r"""
    A probe cannot be read.
    """
    ...

@typing.final
class Pulse:
    @staticmethod
    def step(*, low: builtins.float, high: builtins.float) -> Pulse: ...
    def delay(self, delay: builtins.float) -> Pulse: ...
    def rise(self, rise: builtins.float) -> Pulse: ...
    def fall(self, fall: builtins.float) -> Pulse: ...
    def width(self, width: builtins.float) -> Pulse: ...
    def period(self, period: builtins.float) -> Pulse: ...

@typing.final
class Rail:
    def net(self) -> builtins.str:
        r"""
        The rail's full net name.
        """
    def kind(self) -> typing.Literal['driven', 'source', 'ground']:
        r"""
        How the rail is powered: `"driven"`, `"source"` or `"ground"`.
        """
    def voltages(self) -> builtins.list[builtins.float]:
        r"""
        One voltage per corner for a source rail; empty otherwise.
        """
    def origin(self) -> typing.Literal['declared', 'inferred'] | None:
        r"""
        `"declared"` or `"inferred"` for a source rail; `None` otherwise.
        """
    def driven_by(self) -> builtins.list[builtins.str]:
        r"""
        The pins driving a driven rail; empty otherwise.
        """

@typing.final
class Report:
    r"""
    Every probe's outcome at every corner.
    """
    def outcomes(self) -> builtins.list[Outcome]:
        r"""
        Each probe's outcome, in probe then corner order.
        """
    def __bool__(self) -> builtins.bool:
        r"""
        Whether no check failed.
        """

@typing.final
class Response:
    def frequency(self) -> builtins.list[builtins.float]: ...
    def values(self) -> builtins.list[builtins.complex]: ...
    def gain_db_at(self, frequency: builtins.float) -> builtins.float: ...
    def phase_deg_at(self, frequency: builtins.float) -> builtins.float: ...

@typing.final
class Signal:
    def time(self) -> builtins.list[builtins.float]: ...
    def values(self) -> builtins.list[builtins.float]: ...
    def settles_to(self, target: builtins.float, tolerance: Tolerance, *, window: builtins.float) -> Check:
        r"""
        Whether the signal stays within `tolerance` of `target` over the last
        `window` seconds.
        """
    def overshoot(self, target: builtins.float) -> builtins.float: ...
    def dominant_tone(self) -> Tone:
        r"""
        The strongest sinusoid in this waveform.
        """

class SimulationError(KitestError):
    r"""
    The simulator failed.
    """
    ...

@typing.final
class Sin:
    def __new__(cls, *, offset: builtins.float, amplitude: builtins.float, freq: builtins.float) -> Sin: ...
    def delay(self, delay: builtins.float) -> Sin: ...

@typing.final
class Spectra:
    def node(self, node: builtins.str) -> Response: ...
    def nodes(self) -> builtins.list[builtins.str]: ...

class SupplyError(KitestError):
    r"""
    Power rails cannot be resolved.
    """
    ...

@typing.final
class Tolerance:
    @staticmethod
    def abs(v: builtins.float) -> Tolerance:
        r"""
        An absolute tolerance of `v`.
        """
    @staticmethod
    def percent(p: builtins.float) -> Tolerance:
        r"""
        A tolerance of `p` percent of the target.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Tone:
    def frequency(self) -> Frequency:
        r"""
        The frequency of the dominant sinusoid.
        """
    def amplitude(self) -> Voltage:
        r"""
        The amplitude of the dominant sinusoid, zero to peak.
        """
    def samples_per_cycle(self) -> builtins.float:
        r"""
        Simulator samples per cycle of the dominant sinusoid.
        """

@typing.final
class Tran:
    def __new__(cls, *, step: builtins.float, stop: builtins.float) -> Tran: ...
    def start(self, start: builtins.float) -> Tran:
        r"""
        Discard output before `start` seconds.
        """

@typing.final
class TranSource:
    @staticmethod
    def dc(node: builtins.str, volts: builtins.float) -> TranSource:
        r"""
        Hold `node` at a constant `volts`.
        """
    @staticmethod
    def noisy_dc(node: builtins.str, volts: builtins.float, *, noise: builtins.float) -> TranSource:
        r"""
        Hold `node` at `volts`, with `noise` volts RMS of supply noise.
        """
    @staticmethod
    def pulse(node: builtins.str, pulse: Pulse) -> TranSource: ...
    @staticmethod
    def sin(node: builtins.str, sin: Sin) -> TranSource: ...
    @staticmethod
    def kick(node: builtins.str, amps: builtins.float) -> TranSource:
        r"""
        Inject a brief current impulse of `amps` into `node`, to start an
        oscillator without moving its operating point.
        """

@typing.final
class Transient:
    def node(self, node: builtins.str) -> Signal: ...
    def nodes(self) -> builtins.list[builtins.str]: ...

@typing.final
class Voltage:
    def volts(self) -> builtins.float:
        r"""
        The value in volts.
        """
    def near(self, expected: builtins.float, tolerance: Tolerance) -> Check:
        r"""
        Whether the voltage is within `tolerance` of `expected`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Sweep(enum.Enum):
    Dec = ...
    Oct = ...
    Lin = ...

def check_project(project: builtins.str) -> Report:
    r"""
    Check every probe in the KiCad project at `project`, a directory or a
    `.kicad_sch` file, against its `Expect` field.
    """

def export_design(sch: builtins.str) -> Design:
    r"""
    Read the KiCad schematic at `sch` as kitest sees it.
    """

def version() -> builtins.str:
    r"""
    Returns the kitest version string.
    """

