[package]
name = "kitest"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
kitest-measure = { version = "0.0.0", path = "../kitest-measure" }
kitest-scope = { version = "0.0.0", path = "../kitest-scope", default-features = false }
num-complex = "0.4.6"
realfft = "3.5.0"
roxmltree = "0.21.1"
serde = { version = "1.0.229", features = ["derive"] }
tempfile = "3.27.0"
thiserror = "2"
toml = "1.1.6"

[dev-dependencies]
rand = "0.10.3"
rand_distr = "0.6.0"
